apiVersion: batch/v1
kind: Job
metadata:
  name: cilium-nodeperf
  namespace: cilium
spec:
  template:
    spec:
      containers:
      - args:
        - "--etcd-config=/var/lib/etcd-config/etcd.config"
        - "--initial-count=1000"
        - "--additional-count=1"
        command:
        - "./node-discovery-perf"
        image: nebril/cilium-nodes-perf
        imagePullPolicy: IfNotPresent
        name: nodeperf
        volumeMounts:
        - mountPath: /var/lib/etcd-config
          name: etcd-config-path
          readOnly: true
        - mountPath: /var/lib/etcd-secrets
          name: etcd-secrets
          readOnly: true
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: etcd-config
            path: etcd.config
          name: cilium-config
        name: etcd-config-path
      - name: etcd-secrets
        secret:
          defaultMode: 420
          optional: true
          secretName: cilium-etcd-secrets
