apiVersion: v1
kind: Pod
metadata:
  name: cilium-nodeperf
  namespace: cilium
spec:
  containers:
  - args:
    - "10000"
    command:
    - sleep
    image: nebril/cilium-nodes-perf
    imagePullPolicy: Always
    name: nodeperf
    volumeMounts:
    - mountPath: /var/lib/etcd-config
      name: etcd-config-path
      readOnly: true
    - mountPath: /var/lib/etcd-secrets
      name: etcd-secrets
      readOnly: true
  restartPolicy: Always
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: etcd-config
        path: etcd.config
      name: cilium-config
    name: etcd-config-path
  - name: etcd-secrets
    secret:
      defaultMode: 420
      optional: true
      secretName: cilium-etcd-secrets
